# Site
name: "Dotworld Technologies"
title: "Blog"
description: "Checkout the blog to know more about Dotworld Technologies"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
google_analytics: 'UA-118349009-5'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
# include: ["_pages"]
permalink: /:title/

# Authors
authors:
  naveens:
    name: Naveen Sakthivel
    display_name: Naveen Sakthivel
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: naveen@dotworld.in
    web: https://naveens.co.in
    twitter: https://twitter.com/naveen_robotics
    description: "Ex-Accenture, CTO @ Dotworld Technologies, Studying MTech @ BITS Pilani. JS, React, C#, Java, Python, Android and whatnot."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
